version: "3.3"
networks:
    graph-starter:
services:
    postgresql:
        restart: always
        image: "postgres"
        ports: 
         - "5432:5432"
        environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=graphdb
        volumes: 
         - /var/lib/postgresql/data
        networks: 
         - graph-starter 
